apiVersion: v1
kind: Service
metadata:
  name: rancher-ci-test-web
  labels:
    app: rancher-ci-test-web
spec:
  selector:
    app: rancher-ci-test-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
