apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-ci-test-web
  labels:
    app: rancher-ci-test-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-ci-test-web
  template:
    metadata:
      labels:
        app: rancher-ci-test-web
    spec:
      containers:
      - name: rancher-ci-test-web
        image: chicker94/rancher-ci-test:41261c5
        ports:
        - containerPort: 8080

